[package]
name = "zfs-cli"
version = "0.1.0"
authors = ["Jacob Hughes <j@jacobhughes.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zfs-rs = { path = "../zfs-rs", version = "0.1.0" }
